[2025-04-26T02:18:47.818+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T02:18:47.853+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-26T02:18:36.034456+00:00 [queued]>
[2025-04-26T02:18:47.872+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-26T02:18:36.034456+00:00 [queued]>
[2025-04-26T02:18:47.873+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-26T02:18:47.898+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_stock_prices> on 2025-04-26 02:18:36.034456+00:00
[2025-04-26T02:18:47.914+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_ETL', 'load_stock_prices', 'manual__2025-04-26T02:18:36.034456+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmpus9__2v5']
[2025-04-26T02:18:47.917+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask load_stock_prices
[2025-04-26T02:18:47.918+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3957) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-26T02:18:47.919+0000] {standard_task_runner.py:72} INFO - Started process 3960 to run task
[2025-04-26T02:18:47.987+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-26T02:18:36.034456+00:00 [running]> on host 30114da9400b
[2025-04-26T02:18:48.190+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_ETL' AIRFLOW_CTX_TASK_ID='load_stock_prices' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T02:18:36.034456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T02:18:36.034456+00:00'
[2025-04-26T02:18:48.191+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-26T02:18:48.678+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-26T02:18:48.968+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-26T03:19:18.545+0000] {job.py:229} INFO - Heartbeat recovered after 2734.21 seconds
[2025-04-26T03:19:20.945+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-04-26T03:19:20.981+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-26T03:19:21.156+0000] {process_utils.py:132} INFO - Sending 15 to group 3960. PIDs of all processes in the group: [3960]
[2025-04-26T03:19:21.167+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3960
[2025-04-26T03:19:21.885+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-26T03:19:24.042+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tesla_stock_etl.py", line 70, in load_stock_prices
    cur.execute(sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 984, in execute
    ret = self._execute_helper(query, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 695, in _execute_helper
    ret = self._connection.cmd_query(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1350, in cmd_query
    ret = self.rest.request(
          ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 491, in request
    return self._post_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 739, in _post_request
    ret = self.fetch(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 854, in fetch
    ret = self._request_exec_wrapper(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 896, in _request_exec_wrapper
    return_object = self._request_exec(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py", line 1059, in _request_exec
    raw_ret = session.request(
              ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/ssl_wrap_socket.py", line 77, in ssl_wrap_socket_with_ocsp
    ret = ssl_.ssl_wrap_socket(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 458, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/home/airflow/.local/lib/python3.12/site-packages/OpenSSL/SSL.py", line 959, in load_verify_locations
    load_result = _lib.SSL_CTX_load_verify_locations(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-26T03:19:24.460+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tesla_ETL, task_id=load_stock_prices, run_id=manual__2025-04-26T02:18:36.034456+00:00, execution_date=20250426T021836, start_date=20250426T021847, end_date=20250426T031924
[2025-04-26T03:19:24.872+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-26T03:19:25.078+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3960, status='terminated', exitcode=2, started='02:18:47') (3960) terminated with exit code 2
